```{r}
library(text)
library(reticulate)
library(tidyverse)
library(ggtext)
library(showtext)
library(glue)

font_add_google("Raleway", "rale")
showtext_auto()
colscheme <- c("#1c9a89", "#eb5700")
```

```{r}
text::textrpp_install()
reticulate::conda_list()
text::textrpp_initialize(save_profile = TRUE)
textEmbed("hello")

py_install("pandas")
py_install("yfinance")
py_install("numpy")
source_python('helpers/helpers.py')
source_python('prediction.py')

companies <- companies_df
```

```{r warning = F, message = F}
growth_status <- function(name) {
  data <- get_prices_by_ceo_name(name)
  
  com_bef <- as.data.frame(data[3]) |>
        mutate(val = "Company", status = "Before") |>
        rename(Value = Adj.Close)

  com_aft <- as.data.frame(data[4]) |>
        mutate(val = "Company", status = "After") |>
        rename(Value = Adj.Close)
  
  avg_bef <- mean(com_bef$Value)
  avg_aft <- mean(com_aft$Value)
  status <- ifelse(avg_bef > avg_aft, "Before", "After")
  return(status)
}

growth_graph_df <- companies |>
  filter(FemaleCEO == "yes") |>
  rowwise() |>
  mutate(growth = growth_status(CEO))

growth_graph_df <- growth_graph_df |>
  filter(!is.na(growth)) |>
  select(Sector, growth) |> ungroup()

stacked_bar <- growth_graph_df |>
  select(growth, Sector) |>
  group_by(growth, Sector) |>
  count()

dot_title <- glue("Is average growth higher <span style='color:{colscheme[2]}'>**before**</span> or <span style='color:{colscheme[1]}'>**after**</span> a female CEO is hired?")
dot_sub <- "*Comparing growth in the 250 days leading up to the hire of a female CEO vs the 250 days after*"
  
ggplot(growth_graph_df, aes(x = Sector, fill = growth)) +
  coord_flip() +
  geom_dotplot(dotsize = 0.8, stackratio = 3, stackgroups = TRUE) +
  scale_fill_manual(values = colscheme) +
  scale_x_discrete(limits=rev) +
  labs(title = dot_title, subtitle = dot_sub, y = "Count of Companies") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(family = "rale"),
        plot.title = element_markdown(),
        plot.subtitle = element_markdown(size = 8),
        legend.position = "none")
```


```{r growth-graph, message = F, warning = F, error = F}
create_graph <- function(name) {
    graph_data <- get_continuous_prices_by_ceo_name(name)
    ind_bef <- as.data.frame(graph_data[1]) |>
        mutate(val = "Industry Avg", status = "Before") |>
        rename(Value = industry_avg)

    ind_aft <- as.data.frame(graph_data[2]) |>
        mutate(val = "Industry Avg", status = "After") |>
        rename(Value = industry_avg)

    com_bef <- as.data.frame(graph_data[3]) |>
        mutate(val = "Company", status = "Before") |>
        rename(Value = Adj.Close)

    com_aft <- as.data.frame(graph_data[4]) |>
        mutate(val = "Company", status = "After") |>
        rename(Value = Adj.Close)

    ind_bef <- cbind(Day = rownames(ind_bef), ind_bef)
    rownames(ind_bef) <- 1:nrow(ind_bef)

    ind_aft <- cbind(Day = rownames(ind_aft), ind_aft)
    rownames(ind_aft) <- 1:nrow(ind_aft)

    com_bef <- cbind(Day = rownames(com_bef), com_bef)
    rownames(com_bef) <- 1:nrow(com_bef)

    com_aft <- cbind(Day = rownames(com_aft), com_aft)
    rownames(com_aft) <- 1:nrow(com_aft)

    df <- bind_rows(ind_bef, ind_aft, com_bef, com_aft) |> mutate(time = "Actual")
    df$Day <- as.numeric(as.character(df$Day))
    
    company_name <- companies |> filter(CEO == name) |> pull(Company)
    hiredate <- ceos_df |> filter(Company == company_name) |>
      pull(`hire date (female only)`)
    
    fit_and_predict_inference_results <- fit_and_predict_inference_results |>
      rename(CEO = name)
    
    pred_data <- fit_and_predict_inference_results |> filter(CEO == name) |>
      mutate(time = "Predicted")
    pred_data$Day <- as.numeric(as.character(pred_data$Day))
    print(pred_data)
    
    avg_bef <- mean(com_bef$Value)
    avg_aft <- mean(com_aft$Value)
    status <- ifelse(avg_bef > avg_aft, "before", "after")
    
    title <- glue("Growth Before & After: **{company_name}**")
    sub <- glue("***{name}*** *started as CEO on {hiredate}*")
    capt <- glue("*On average, the company was growing more* ***{status}*** *the hire*")

    ggplot(df, aes(x = Day, y = Value, color = val, linetype = time)) +
      geom_line() +
      geom_line(data = pred_data) +
      facet_wrap(~factor(status, levels=c("Before", "After"))) +
      scale_color_manual(values = colscheme) +
      labs(color = "",
           linetype = "",
           title = title,
           subtitle = sub,
           y = "Percent Growth",
           x = "Day",
           caption = capt) +
      theme_bw() +
      theme(text = element_text(family = "rale"),
            plot.subtitle = element_markdown(),
            plot.title = element_markdown(),
            panel.grid = element_blank(),
            plot.caption = element_markdown(hjust = 0.5))
}

create_graph("Karen S. Lynch")
```

```{r lilly-chart-remakes}
# sector (all companies)
ggplot(companies) +
  geom_bar(aes(y = Sector), fill = "steelblue", color = "black", width = 0.7) +
  scale_y_discrete(limits = rev) +
  scale_x_continuous(limits = c(0, 140), breaks = seq(0, 140, by = 20)) +
  labs(x = "Number of Companies", y = "", title = "Distribution of Sector") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        text = element_text(family = "rale"),
        plot.title = element_text(face = "bold"))

# sector (female ceos)
ggplot(companies |> filter(FemaleCEO == "yes")) +
  geom_bar(aes(y = Sector), fill = "steelblue", color = "black", width = 0.7) +
  scale_y_discrete(limits = rev) +
  scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, by = 2)) +
  labs(x = "Number of Companies", y = "", title = "Distribution of Sector",
       subtitle = "Companies with Female CEOs") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        text = element_text(family = "rale"),
        plot.title = element_text(face = "bold"))

# employee count (all companies)
discretize <- function(x, width) {
  cut(x, breaks = seq(0, max(x) + width, by = width),
      include.lowest = FALSE, right = TRUE, labels = seq(width, max(x) + width, width))
}
ggplot(companies |> filter(Number_of_employees <= 100000) |>
         mutate(empcount = discretize(Number_of_employees, 2000))) +
  geom_bar(aes(x = empcount), fill = "steelblue", width = 0.5) +
  labs(x = "Number of Employees (Upper Bound)",
       y = "Number of Companies",
       title = "Distribution of Employee Count") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        text = element_text(family = "rale"),
        plot.title = element_text(face = "bold"),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# yoe (female ceos)
ggplot(ceos_df |> filter(YOE != "-1")) +
  geom_bar(aes(x = YOE), fill = "steelblue", width = 0.5) +
  scale_x_continuous(breaks = seq(0, 15, by = 1)) +
  labs(x = "YOE",
       y = "Number of Companies",
       title = "Distribution of Years of Experience",
       subtitle = "Companies with Female CEOs") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        text = element_text(family = "rale"),
        plot.title = element_text(face = "bold"))

# exec yoe (female ceos)
ggplot(ceos_df |> filter(`Exec YOE` != "-1")) +
  geom_bar(aes(x = `Exec YOE`), fill = "steelblue", width = 0.5) +
  scale_x_continuous(breaks = seq(0, 30, by = 1)) +
  labs(x = "Exec YOE",
       y = "Number of Companies",
       title = "Distribution of Executive Years of Experience",
       subtitle = "Companies with Female CEOs") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        text = element_text(family = "rale"),
        plot.title = element_text(face = "bold"))

# hire year (female ceos)
ceos_df$hire_year <- substr(ceos_df$`hire date (female only)`,
                            nchar(ceos_df$`hire date (female only)`) - 3,
                            nchar(ceos_df$`hire date (female only)`))
ggplot(ceos_df) +
  geom_bar(aes(x = hire_year), fill = "steelblue", width = 0.5) +
  #scale_x_continuous(breaks = seq(0, 30, by = 1)) +
  labs(x = "CEO Hire Year",
       y = "Number of Companies",
       title = "Distribution of Hire Year of CEO",
       subtitle = "Companies with Female CEOs") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        text = element_text(family = "rale"),
        plot.title = element_text(face = "bold"))
```

